services:
  scribbly:
    image: postgres:16.2
    container_name: scribbly
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
